import type { BootstrapData } from './types';

export const demoData: BootstrapData = {
  organization: {
    id: 'nc-golden-bears',
    name: 'North Carolina Golden Bears',
    shortName: 'NC Golden Bears',
    website: 'https://www.ncgoldenbears.com',
    logoUrl:
      'https://crossbar.s3.amazonaws.com/organizations/405/uploads/bab3717b-3442-4868-86c1-30477aa79791.png?versionId=bx8Qi4fv9_5fzSrFRlOTPPoRMXnlQX1v',
    primaryColor: '#184d3b',
    secondaryColor: '#b8952f',
    tryoutWindowLabel: 'May 1-3, 2026',
    tryoutWindowStart: '2026-05-01',
    tryoutWindowEnd: '2026-05-03',
    tryoutBirthYearYoungest: '2017',
    tryoutBirthYearOldest: '2008',
    intakeIntro:
      'Please complete the brief form below. Responses are intended to help staff understand what type of environment may best accelerate the player\'s growth, along with coaching and learning preferences and any practical considerations ahead of tryouts. There are no "right" answers, and responses do not determine placement. This is not a scored part of tryouts and does not replace on-ice evaluation. The goal is simply better information in service of better development.',
  },
  access: {
    email: 'demo@ncgoldenbears.com',
    roles: ['parent'],
    mode: 'demo',
    activeOrganizationId: 'nc-golden-bears',
    organizations: [
      {
        organizationId: 'nc-golden-bears',
        name: 'North Carolina Golden Bears',
        shortName: 'NC Golden Bears',
        roles: ['parent'],
      },
    ],
    linkedOrganizations: ['NC Golden Bears'],
    canManageOrganization: false,
    canManagePlatform: false,
  },
  user: {
    userId: 'demo-user',
    email: 'demo@ncgoldenbears.com',
    firstName: 'Brian',
    lastName: 'Wasikowski',
    contactEmail: 'demo@ncgoldenbears.com',
    phoneNumber: '',
    smsOptIn: false,
    primaryRole: 'parent',
    accountStatus: 'ACTIVE',
    createdAt: '2026-04-08T16:00:00.000Z',
    updatedAt: '2026-04-08T16:00:00.000Z',
  },
  players: [
    {
      id: 'demo-player-1',
      relationship: 'parent',
      profile: {
        playerName: 'Mason Hart',
        firstName: 'Mason',
        lastName: 'Hart',
        birthYear: '2012',
        gender: 'Male',
        primaryPosition: 'Forward',
        handedness: 'Left',
        firstYearPlayingHockey: '2018',
        currentTeam: '12U AA',
        positions: 'Forward, open to center or wing',
        completedBy: 'Player and Parent together',
        bestContactEmail: 'demo@ncgoldenbears.com',
        phoneNumber: '',
        smsOptIn: false,
        teamHistory: [
          {
            id: 'team-1',
            seasonLabel: '2025-26',
            teamName: 'NC Golden Bears 12U AA',
            positionPlayed: 'Forward',
          },
          {
            id: 'team-2',
            seasonLabel: '2024-25',
            teamName: 'Carolina Stars 12U A',
            positionPlayed: 'Wing',
          },
        ],
        latestHeightFeet: '5',
        latestHeightInches: '2',
        latestWeightPounds: '105',
        physicalHistory: [
          {
            id: 'measure-1',
            recordedAt: '2026-04-08T16:10:00.000Z',
            heightFeet: '5',
            heightInches: '2',
            weightPounds: '105',
          },
        ],
      },
      intake: {
        status: 'draft',
        updatedAt: '2026-04-08T16:15:00.000Z',
        submittedAt: null,
        answers: {
          nextSeasonOutcome: 'Skill development',
          developmentSetting: 'Balanced-growth setting',
          preferredRole: 'Consistent regular role',
          coachingStyle: 'Balanced mix',
          participationConsiderations: 'Minor scheduling considerations',
          participationConsiderationsNote: 'One summer vacation week is already planned.',
          additionalInsight: 'Mason responds well to clear teaching and steady accountability.',
        },
      },
      createdAt: '2026-04-08T16:00:00.000Z',
      updatedAt: '2026-04-08T16:15:00.000Z',
      sentInvites: [
        {
          id: 'demo-invite-1',
          playerId: 'demo-player-1',
          playerName: 'Mason Hart',
          invitedEmail: 'mason.hart@example.com',
          invitedRole: 'player',
          invitedByUserId: 'demo-user',
          invitedByLabel: 'demo@ncgoldenbears.com',
          status: 'pending',
          createdAt: '2026-04-08T16:20:00.000Z',
          acceptedAt: null,
        },
      ],
    },
  ],
  receivedInvites: [],
  admin: {
    canClaimOrganizationAdmin: true,
    hasOrganizationAdmin: false,
    summary: {
      totalPlayers: 1,
      submittedIntakes: 0,
      draftIntakes: 1,
      pendingInvites: 1,
    },
  },
};
