import type { CondoOpsData } from './types';

export const demoData: CondoOpsData = {
  dashboard: {
    propertyName: 'Myrtle Beach Condo',
    monthLabel: 'April 2026',
    revenue: 8425,
    expenses: 3112,
    netIncome: 5313,
    occupancy: 0.78,
    maintenanceReserve: 640,
    nextArrival: '2026-04-11',
    nextDeparture: '2026-04-15',
    propertyNote:
      'Condo Ops is seeded with sample revenue, booking, and maintenance activity so we can shape the product flow before connecting live data sources.',
    alerts: [
      {
        title: 'Turnover Window Is Tight',
        detail: 'The April 15 departure and next arrival leave less than four hours for a full clean.',
        severity: 'warning',
      },
      {
        title: 'Month Is Profitable',
        detail: 'Projected net income is tracking above the last 90-day average.',
        severity: 'success',
      },
      {
        title: 'Owner Statement Draft Due Friday',
        detail: 'Use the ledger tab to review reimbursable items before the monthly summary is exported.',
        severity: 'info',
      },
    ],
  },
  bookings: [
    {
      id: 'stay-1042',
      guestName: 'Jordan & Casey',
      source: 'VRBO',
      checkIn: '2026-04-11',
      checkOut: '2026-04-15',
      nights: 4,
      grossAmount: 1625,
      status: 'Upcoming',
    },
    {
      id: 'stay-1043',
      guestName: 'The Alvarez Family',
      source: 'Airbnb',
      checkIn: '2026-04-18',
      checkOut: '2026-04-23',
      nights: 5,
      grossAmount: 2140,
      status: 'Confirmed',
    },
    {
      id: 'stay-1044',
      guestName: 'Owner Block',
      source: 'Direct',
      checkIn: '2026-05-02',
      checkOut: '2026-05-05',
      nights: 3,
      grossAmount: 0,
      status: 'Owner Stay',
    },
  ],
  transactions: [
    {
      id: 'txn-2001',
      date: '2026-04-02',
      category: 'Rental Income',
      vendor: 'VRBO Payout',
      amount: 2480,
      type: 'income',
    },
    {
      id: 'txn-2002',
      date: '2026-04-04',
      category: 'Cleaning',
      vendor: 'Coastal Turnovers LLC',
      amount: 185,
      type: 'expense',
    },
    {
      id: 'txn-2003',
      date: '2026-04-06',
      category: 'HOA',
      vendor: 'Ocean Dunes HOA',
      amount: 640,
      type: 'expense',
    },
    {
      id: 'txn-2004',
      date: '2026-04-07',
      category: 'Maintenance',
      vendor: 'Atlantic Appliance Repair',
      amount: 210,
      type: 'expense',
    },
    {
      id: 'txn-2005',
      date: '2026-04-08',
      category: 'Rental Income',
      vendor: 'Airbnb Payout',
      amount: 1795,
      type: 'income',
    },
  ],
  tasks: [
    {
      id: 'task-3001',
      title: 'Confirm cleaner for April 15 turnover',
      dueDate: '2026-04-13',
      owner: 'Property Manager',
      priority: 'High',
      status: 'Open',
    },
    {
      id: 'task-3002',
      title: 'Order replacement balcony chair cushions',
      dueDate: '2026-04-20',
      owner: 'Family Admin',
      priority: 'Medium',
      status: 'In Progress',
    },
    {
      id: 'task-3003',
      title: 'Schedule spring HVAC inspection',
      dueDate: '2026-04-24',
      owner: 'Maintenance Vendor',
      priority: 'Medium',
      status: 'Open',
    },
  ],
  access: {
    email: 'demo@wasikowski.com',
    roles: ['admin', 'user'],
    mode: 'demo',
    canManageUsers: true,
  },
};

